/**
 * =============================================================================
 * EMAIL SERVICE - Gmail SMTP Integration
 * =============================================================================
 *
 * PURPOSE:
 * This service handles all outgoing emails for the A&L Bakes platform using
 * Gmail SMTP via Nodemailer. This is a simpler approach for development and
 * small-scale production.
 *
 * HOW IT WORKS:
 * 1. Backend calls a function here (e.g., sendOrderConfirmationEmail)
 * 2. Function builds HTML + plain text email content
 * 3. Nodemailer sends the email via Gmail SMTP
 * 4. Gmail delivers to recipient's inbox
 *
 * GMAIL SETUP REQUIRED:
 * 1. Enable 2-Factor Authentication on your Google account
 * 2. Generate an App Password: Google Account → Security → App Passwords
 * 3. Set environment variables:
 *    - GMAIL_USER: your Gmail address (e.g., albakes.local@gmail.com)
 *    - GMAIL_APP_PASSWORD: the 16-character app password (no spaces)
 *
 * FILES THAT USE THIS SERVICE:
 * - orders.controller.js → sendOrderConfirmationEmail, sendAdminNewOrderNotification
 * - customer.auth.controller.js → sendPasswordResetEmail, sendWelcomeEmail
 *
 * =============================================================================
 */

import nodemailer from "nodemailer";

/**
 * Gmail SMTP Transporter Configuration
 *
 * Uses Gmail's SMTP server with App Password authentication.
 * App Passwords are required because Gmail blocks "less secure apps".
 *
 * WHY APP PASSWORD?
 * - Regular password won't work with 2FA enabled
 * - App Password is a 16-character code generated by Google
 * - More secure than allowing "less secure app access"
 */
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.GMAIL_USER || "albakes.local@gmail.com",
    pass: process.env.GMAIL_APP_PASSWORD, // 16-char app password, no spaces
  },
});

/**
 * Sender Configuration
 */
const SENDER_EMAIL = process.env.GMAIL_USER || "albakes.local@gmail.com";
const SENDER_NAME = "A&L Bakes";

/**
 * =============================================================================
 * CORE EMAIL SENDING FUNCTION
 * =============================================================================
 *
 * This is the base function all other email functions use.
 * It handles the actual SMTP connection via Nodemailer.
 *
 * @param {string} to - Recipient email address
 * @param {string} subject - Email subject line
 * @param {string} html - HTML version of email (for modern email clients)
 * @param {string} text - Plain text fallback (for older clients/accessibility)
 *
 * WHY BOTH HTML AND TEXT?
 * - Some users disable HTML emails for security
 * - Screen readers work better with plain text
 * - Gmail/Outlook show HTML, but text is the fallback
 */
async function sendEmail({ to, subject, html, text }) {
  const mailOptions = {
    from: `"${SENDER_NAME}" <${SENDER_EMAIL}>`,
    to,
    subject,
    html,
    text,
  };

  /**
   * DEVELOPMENT MODE BYPASS
   *
   * When running locally without Gmail credentials, we don't want the app to crash.
   * Instead, log the email details to console for debugging.
   * This lets developers test the flow without actually sending emails.
   */
  if (!process.env.GMAIL_APP_PASSWORD) {
    console.log("\n========================================");
    console.log("📧 EMAIL (dev mode - not sent)");
    console.log("========================================");
    console.log("To:", to);
    console.log("Subject:", subject);
    console.log("========================================\n");
    return { messageId: "dev-mode-" + Date.now() };
  }

  /**
   * PRODUCTION: Actually send via Gmail SMTP
   */
  try {
    const info = await transporter.sendMail(mailOptions);
    console.log(`✅ Email sent to ${to}, MessageId: ${info.messageId}`);
    return info;
  } catch (error) {
    console.error("❌ Email error:", error);
    throw error;
  }
}

/**
 * =============================================================================
 * PASSWORD RESET EMAIL
 * =============================================================================
 *
 * TRIGGERED BY: customer.auth.controller.js → forgotPassword()
 *
 * FLOW:
 * 1. User clicks "Forgot Password" on login page
 * 2. Backend generates a secure token (stored in DB with expiry)
 * 3. This function sends email with reset link containing token
 * 4. User clicks link → frontend validates token → allows password change
 *
 * SECURITY CONSIDERATIONS:
 * - Token expires in 1 hour (set in auth.controller.js)
 * - Token is single-use (deleted after password change)
 * - Link uses HTTPS in production (via FRONTEND_URL env var)
 *
 * @param {string} email - User's email address
 * @param {string} token - Secure random token for password reset
 * @param {string} firstName - User's name for personalization
 */
export async function sendPasswordResetEmail(email, token, firstName) {
  const resetUrl = `${process.env.FRONTEND_URL || "http://localhost:5173"}/reset-password/${token}`;

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="text-align: center; padding: 20px; background: #1a1a1a;">
        <h1 style="color: #f5a623; margin: 0;">A&L Bakes</h1>
      </div>

      <div style="padding: 30px; background: #fff;">
        <h2 style="color: #333;">Hi ${firstName},</h2>

        <p style="color: #555; line-height: 1.6;">
          We received a request to reset your password for your A&L Bakes account.
          Click the button below to create a new password:
        </p>

        <div style="text-align: center; margin: 30px 0;">
          <a href="${resetUrl}"
             style="display: inline-block;
                    padding: 14px 28px;
                    background: #f5a623;
                    color: #000;
                    text-decoration: none;
                    border-radius: 8px;
                    font-weight: 600;">
            Reset Password
          </a>
        </div>

        <p style="color: #555; line-height: 1.6;">
          This link will expire in <strong>1 hour</strong> for security reasons.
        </p>

        <p style="color: #555; line-height: 1.6;">
          If you didn't request a password reset, you can safely ignore this email.
          Your password will remain unchanged.
        </p>

        <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;" />

        <p style="color: #888; font-size: 12px;">
          If the button doesn't work, copy and paste this link into your browser:<br />
          <a href="${resetUrl}" style="color: #f5a623;">${resetUrl}</a>
        </p>
      </div>

      <div style="text-align: center; padding: 20px; background: #f5f5f5; color: #888; font-size: 12px;">
        <p style="margin: 0;">© ${new Date().getFullYear()} A&L Bakes. All rights reserved.</p>
        <p style="margin: 8px 0 0;">
          <a href="https://www.facebook.com/people/AL-Bakes/61587012191793/" style="color: #f5a623; text-decoration: none;">A&L Bakes on Facebook</a>
        </p>
      </div>
    </div>
  `;

  const text = `
Hi ${firstName},

We received a request to reset your password for your A&L Bakes account.

Click this link to reset your password: ${resetUrl}

This link will expire in 1 hour for security reasons.

If you didn't request a password reset, you can safely ignore this email.

© ${new Date().getFullYear()} A&L Bakes
  `.trim();

  return sendEmail({
    to: email,
    subject: "Reset Your Password - A&L Bakes",
    html,
    text,
  });
}

/**
 * =============================================================================
 * WELCOME EMAIL (NEW USER REGISTRATION)
 * =============================================================================
 *
 * TRIGGERED BY: customer.auth.controller.js → customerRegister()
 *
 * FLOW:
 * 1. User completes registration form
 * 2. Backend creates user account in database
 * 3. This function sends welcome email with account benefits
 * 4. Encourages user to browse menu (CTA button)
 *
 * PURPOSE:
 * - Confirms successful account creation
 * - Builds brand relationship
 * - Drives engagement by linking to menu
 *
 * @param {string} email - New user's email address
 * @param {string} firstName - User's name for personalization
 */
export async function sendWelcomeEmail(email, firstName) {
  const frontendUrl = process.env.FRONTEND_URL || "http://localhost:5173";

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="text-align: center; padding: 20px; background: #1a1a1a;">
        <h1 style="color: #f5a623; margin: 0;">A&L Bakes</h1>
      </div>

      <div style="padding: 30px; background: #fff;">
        <h2 style="color: #333;">Welcome, ${firstName}!</h2>

        <p style="color: #555; line-height: 1.6;">
          Thank you for creating an account with A&L Bakes. We're delighted to have you!
        </p>

        <p style="color: #555; line-height: 1.6;">
          With your account, you can:
        </p>

        <ul style="color: #555; line-height: 1.8;">
          <li>Save your cart for later</li>
          <li>Track your orders</li>
          <li>View your order history</li>
          <li>Leave reviews on products</li>
        </ul>

        <div style="text-align: center; margin: 30px 0;">
          <a href="${frontendUrl}/menu"
             style="display: inline-block;
                    padding: 14px 28px;
                    background: #f5a623;
                    color: #000;
                    text-decoration: none;
                    border-radius: 8px;
                    font-weight: 600;">
            Browse Our Menu
          </a>
        </div>
      </div>

      <div style="text-align: center; padding: 20px; background: #f5f5f5; color: #888; font-size: 12px;">
        <p style="margin: 0;">© ${new Date().getFullYear()} A&L Bakes. All rights reserved.</p>
        <p style="margin: 8px 0 0;">
          <a href="https://www.facebook.com/people/AL-Bakes/61587012191793/" style="color: #f5a623; text-decoration: none;">A&L Bakes on Facebook</a>
        </p>
      </div>
    </div>
  `;

  const text = `
Welcome, ${firstName}!

Thank you for creating an account with A&L Bakes. We're delighted to have you!

With your account, you can:
- Save your cart for later
- Track your orders
- View your order history
- Leave reviews on products

Browse our menu: ${frontendUrl}/menu

© ${new Date().getFullYear()} A&L Bakes
  `.trim();

  return sendEmail({
    to: email,
    subject: "Welcome to A&L Bakes!",
    html,
    text,
  });
}

/**
 * =============================================================================
 * ORDER CONFIRMATION EMAIL
 * =============================================================================
 *
 * TRIGGERED BY: orders.controller.js → createOrderFromSession()
 *
 * FLOW:
 * 1. Customer completes Stripe checkout
 * 2. Stripe redirects to /order-success
 * 3. Backend creates order in database
 * 4. This function sends receipt email to customer
 *
 * EMAIL INCLUDES:
 * - Order ID (for reference)
 * - Itemized list with quantities and prices
 * - Subtotal, delivery fee, and total
 * - Delivery/collection date and method
 * - "Track Your Order" button linking to order tracking page
 *
 * @param {string} email - Customer's email address
 * @param {Object} order - Order details object
 */
export async function sendOrderConfirmationEmail(email, order) {
  const frontendUrl = process.env.FRONTEND_URL || "http://localhost:5173";
  const trackingUrl = `${frontendUrl}/track/${order.id}`;

  const itemsList = order.items
    .map((item) => `• ${item.name} x${item.quantity} - £${(item.line_total_pence / 100).toFixed(2)}`)
    .join("\n");

  const itemsHtml = order.items
    .map(
      (item) => `
      <tr>
        <td style="padding: 10px; border-bottom: 1px solid #eee;">${item.name}</td>
        <td style="padding: 10px; border-bottom: 1px solid #eee; text-align: center;">${item.quantity}</td>
        <td style="padding: 10px; border-bottom: 1px solid #eee; text-align: right;">£${(item.line_total_pence / 100).toFixed(2)}</td>
      </tr>
    `
    )
    .join("");

  const deliveryMethod = order.delivery_method === "delivery" ? "Delivery" : "Collection";
  const deliveryDate = order.delivery_date
    ? new Date(order.delivery_date).toLocaleDateString("en-GB", {
        weekday: "long",
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : "To be confirmed";

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="text-align: center; padding: 20px; background: #1a1a1a;">
        <h1 style="color: #f5a623; margin: 0;">A&L Bakes</h1>
      </div>

      <div style="padding: 30px; background: #fff;">
        <div style="text-align: center; margin-bottom: 20px;">
          <span style="font-size: 48px;">✓</span>
          <h2 style="color: #333; margin: 10px 0;">Order Confirmed!</h2>
        </div>

        <p style="color: #555; line-height: 1.6;">
          Hi ${order.customer_name || "there"},
        </p>

        <p style="color: #555; line-height: 1.6;">
          Thank you for your order! We've received your payment and are preparing your delicious treats.
        </p>

        <div style="background: #f9f9f9; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <p style="margin: 0 0 10px; color: #333;"><strong>Order ID:</strong></p>
          <code style="background: #eee; padding: 8px 12px; border-radius: 4px; font-size: 12px;">${order.id}</code>
        </div>

        <h3 style="color: #333; border-bottom: 2px solid #f5a623; padding-bottom: 10px;">Order Details</h3>

        <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
          <thead>
            <tr style="background: #f5f5f5;">
              <th style="padding: 10px; text-align: left;">Item</th>
              <th style="padding: 10px; text-align: center;">Qty</th>
              <th style="padding: 10px; text-align: right;">Price</th>
            </tr>
          </thead>
          <tbody>
            ${itemsHtml}
          </tbody>
          <tfoot>
            <tr>
              <td colspan="2" style="padding: 10px; text-align: right;"><strong>Subtotal:</strong></td>
              <td style="padding: 10px; text-align: right;">£${(order.subtotal_pence / 100).toFixed(2)}</td>
            </tr>
            ${
              order.delivery_pence > 0
                ? `
            <tr>
              <td colspan="2" style="padding: 10px; text-align: right;">Delivery:</td>
              <td style="padding: 10px; text-align: right;">£${(order.delivery_pence / 100).toFixed(2)}</td>
            </tr>
            `
                : ""
            }
            <tr style="background: #f5a623;">
              <td colspan="2" style="padding: 12px; text-align: right;"><strong>Total:</strong></td>
              <td style="padding: 12px; text-align: right;"><strong>£${(order.total_pence / 100).toFixed(2)}</strong></td>
            </tr>
          </tfoot>
        </table>

        <div style="background: #f9f9f9; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <p style="margin: 0 0 8px;"><strong>${deliveryMethod}:</strong> ${deliveryDate}</p>
          ${order.delivery_method === "pickup" ? '<p style="margin: 0; color: #666;">Collection from: A&L Bakes, London</p>' : ""}
        </div>

        <div style="text-align: center; margin: 30px 0;">
          <a href="${trackingUrl}"
             style="display: inline-block;
                    padding: 14px 28px;
                    background: #f5a623;
                    color: #000;
                    text-decoration: none;
                    border-radius: 8px;
                    font-weight: 600;">
            Track Your Order
          </a>
        </div>

        <p style="color: #555; line-height: 1.6;">
          Questions? Reply to this email or reach out on
          <a href="https://www.facebook.com/people/AL-Bakes/61587012191793/" style="color: #f5a623;">Facebook</a>
        </p>
      </div>

      <div style="text-align: center; padding: 20px; background: #f5f5f5; color: #888; font-size: 12px;">
        <p style="margin: 0;">© ${new Date().getFullYear()} A&L Bakes. All rights reserved.</p>
        <p style="margin: 8px 0 0;">
          <a href="https://www.facebook.com/people/AL-Bakes/61587012191793/" style="color: #f5a623; text-decoration: none;">A&L Bakes on Facebook</a>
        </p>
      </div>
    </div>
  `;

  const text = `
Order Confirmed!

Hi ${order.customer_name || "there"},

Thank you for your order! We've received your payment and are preparing your delicious treats.

Order ID: ${order.id}

Order Details:
${itemsList}

Subtotal: £${(order.subtotal_pence / 100).toFixed(2)}
${order.delivery_pence > 0 ? `Delivery: £${(order.delivery_pence / 100).toFixed(2)}` : ""}
Total: £${(order.total_pence / 100).toFixed(2)}

${deliveryMethod}: ${deliveryDate}

Track your order: ${trackingUrl}

Questions? Reach out on Facebook: https://www.facebook.com/people/AL-Bakes/61587012191793/

© ${new Date().getFullYear()} A&L Bakes
  `.trim();

  return sendEmail({
    to: email,
    subject: `Order Confirmed #${order.id.slice(0, 8)} - A&L Bakes`,
    html,
    text,
  });
}

/**
 * =============================================================================
 * ADMIN NEW ORDER NOTIFICATION
 * =============================================================================
 *
 * TRIGGERED BY: orders.controller.js → createOrderFromSession()
 *
 * PURPOSE:
 * Alerts bakery owner immediately when a new order comes in.
 * This enables quick order preparation and improves customer experience.
 *
 * @param {Object} order - Order details
 */
export async function sendAdminNewOrderNotification(order) {
  const adminEmail = process.env.ADMIN_EMAIL || SENDER_EMAIL;
  const frontendUrl = process.env.FRONTEND_URL || "http://localhost:5173";

  const itemsList = order.items
    .map((item) => `• ${item.name} x${item.quantity}`)
    .join("\n");

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="text-align: center; padding: 20px; background: #1a1a1a;">
        <h1 style="color: #f5a623; margin: 0;">🔔 New Order!</h1>
      </div>

      <div style="padding: 30px; background: #fff;">
        <h2 style="color: #333;">Order #${order.id.slice(0, 8)}</h2>

        <div style="background: #e8f5e9; padding: 15px; border-radius: 8px; margin: 20px 0;">
          <p style="margin: 0; color: #2e7d32;"><strong>💰 Total: £${(order.total_pence / 100).toFixed(2)}</strong></p>
        </div>

        <p><strong>Customer:</strong> ${order.customer_name || "N/A"}</p>
        <p><strong>Email:</strong> ${order.customer_email}</p>
        <p><strong>Method:</strong> ${order.delivery_method === "delivery" ? "🚗 Delivery" : "🏪 Collection"}</p>
        <p><strong>Date:</strong> ${order.delivery_date || "TBC"}</p>

        <h3 style="border-bottom: 2px solid #f5a623; padding-bottom: 10px;">Items:</h3>
        <pre style="background: #f5f5f5; padding: 15px; border-radius: 8px;">${itemsList}</pre>

        <div style="text-align: center; margin: 30px 0;">
          <a href="${frontendUrl}/admin"
             style="display: inline-block;
                    padding: 14px 28px;
                    background: #f5a623;
                    color: #000;
                    text-decoration: none;
                    border-radius: 8px;
                    font-weight: 600;">
            View in Dashboard
          </a>
        </div>
      </div>
    </div>
  `;

  const text = `
🔔 NEW ORDER!

Order #${order.id.slice(0, 8)}
Total: £${(order.total_pence / 100).toFixed(2)}

Customer: ${order.customer_name || "N/A"}
Email: ${order.customer_email}
Method: ${order.delivery_method === "delivery" ? "Delivery" : "Collection"}
Date: ${order.delivery_date || "TBC"}

Items:
${itemsList}

View in dashboard: ${frontendUrl}/admin
  `.trim();

  return sendEmail({
    to: adminEmail,
    subject: `🔔 New Order #${order.id.slice(0, 8)} - £${(order.total_pence / 100).toFixed(2)}`,
    html,
    text,
  });
}
